### PR TITLE
Character set fixe !!!

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**

### CODE REVIEW

**Comment by dinkc64** [comment]
hmm, it didn't change the character set ?

**Comment by BenjaminSiskoo** [comment]
With notepad, I saved the file with the option : UTF8 with BOm and it seems to work.

Here the file I sent to to newton and it worked for him : 

[French.zip](https://github.com/finalburnneo/FBNeo-translations/files/4405884/French.zip)

**Comment by dinkc64** [comment]
hmm, even this one looks the same broken way :(
fb

**Comment by BenjaminSiskoo** [comment]
Weird :( 

I dl the last debug release. I copy paste this file and it works (Windows 10 - 64 Bits).

[French.zip](https://github.com/finalburnneo/FBNeo-translations/files/4405970/French.zip)

fbneodebug

**Comment by dinkc64** [comment]
I see the problem - BOM was missing - I added it (via git), see if new file is OK on your side?

**Comment by BenjaminSiskoo** [comment]
Sound good with FB debug :)

Great job :)

**Comment by dinkc64** [comment]
[DEBUG] version only has a problem with french.flt in the Misc menu near the bottom, due to the added debug options.  But it's mostly fine.  I'm still not sure how to make the language file compatible with both.  Thinking about it though... :)

**Comment by BenjaminSiskoo** [comment]
Good luck with that ^^

I tested FB Neo and found some french strings size problems. I don't really know how to handle this. French and german language are more complicate than english, and sometimes, translations are not properly displayed.

**Comment by dinkc64** [comment]
Ok, I uploaded new French.flt, it will only work with latest git-fbn(probably 1hr before exe's are built by appveyor etc) - but, it will work for normal/debug builds now.  (some ID's got renumbered).  I just need to do some testing to make sure I didn't make new bugs.... 

BenjaminSiskoo, can you show me a screencapture where the problems are?  I will try to help fix it.

best regards,
- dink

**Comment by BenjaminSiskoo** [comment]
Great news again :)

Endusers use Debug release, weird ^^

Here the first picture 

Inputs :  
fbn_input

Red : we can have this : Sauveg. les Réglages
Blue : I guess you can resize without any problem

**Comment by BenjaminSiskoo** [comment]
fbn_input2

Red : dialog	  52 "" {
        //-- "Grab mouse"

Grab in french is too long. And I cant decrease the size. Or I could write : Souris (Mouse) butit means nothing

Blue :       3	   3 ""
        //-- "Clear Lock"

Same problem. I could change the translation by : Verouillage

**Comment by BenjaminSiskoo** [comment]
Missing strings in your template : 

fbn_recordinput

**Comment by BenjaminSiskoo** [comment]
Record AVI

fbn_recordavi

Red : missing string in your template
Blue : I can't decrease the sentence or it means nothing

**Comment by BenjaminSiskoo** [comment]
Select skin 

fbn_selectskin

Red : missing strings in your template.

**Comment by BenjaminSiskoo** [comment]
Download language : 

fbn_dllanguage

Red : missing strings in your template

**Comment by dinkc64** [comment]
Thanks, I'll see if I can figure how to improve this, but for next day or 2 I need to finish up new drivers :)

**Comment by BenjaminSiskoo** [comment]
do not rush, take your time :)

**Pull request merged**
